global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus-blockchain"
    scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "node_exporter-blockchain"
    static_configs:
      - targets: ["node_exporter:9100"]

  - job_name: "cadvisor-blockchain"
    static_configs:
      - targets: ["cadvisor:8080"]
