global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
      - targets: ["prometheus-orchestrator:9090"]

  - job_name: "node_exporter"
    static_configs:
      - targets: ["node_exporter-orchestrator:9100"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor-orchestrator:8080"]

  - job_name: "livepeer"
    metrics_path: /metrics
    static_configs:
      - targets: ["orchestrator:7936"]
