version: "3.8"

services:
  geth-node:
    image: ethereum/client-go:latest
    container_name: "geth-node"
    restart: unless-stopped
    volumes:
      - geth:/root/.ethereum
      - '/etc/passwd:/etc/passwd:ro'
      - '/etc/group:/etc/group:ro'
    ports:
      # HTTP server / GraphQL API
      - 8545:8545
      # Network listening port (P2P networking)
      - 30303:30303
    command:
      [
        "--syncmode=light",
        "--cache=8192",
        "--http",
        "--http.api=personal,eth,net,web3",
        "--http.addr=geth-node",
        "--http.vhosts=*",
        "--metrics",
        "--mainnet",
        "--maxpeers=100",
        "--datadir=/root/.ethereum"
      ]
volumes:
  geth:
    external: true
  
networks:
  default:
    name: blockchain
    external: true
